/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteImport } from './routes/_panel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PanelIndexRouteImport } from './routes/_panel.index'
import { Route as PanelAppsAppIdRouteImport } from './routes/_panel.apps.$appId'
import { Route as PanelProjectsProjectIdRouteImport } from './routes/_panel.projects.$projectId'

const PanelRoute = PanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAppsAppIdRoute = PanelAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => PanelRoute,
} as any)
const PanelProjectsProjectIdRoute = PanelProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => PanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PanelIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/apps/$appId': typeof PanelAppsAppIdRoute
  '/projects/$projectId': typeof PanelProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/': typeof PanelIndexRoute
  '/apps/$appId': typeof PanelAppsAppIdRoute
  '/projects/$projectId': typeof PanelProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_panel': typeof PanelRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_panel/': typeof PanelIndexRoute
  '/_panel/apps/$appId': typeof PanelAppsAppIdRoute
  '/_panel/projects/$projectId': typeof PanelProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/setup' | '/apps/$appId' | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/setup' | '/' | '/apps/$appId' | '/projects/$projectId'
  id:
    | '__root__'
    | '/_panel'
    | '/login'
    | '/setup'
    | '/_panel/'
    | '/_panel/apps/$appId'
    | '/_panel/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PanelRoute: typeof PanelRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/': {
      id: '/_panel/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/apps/$appId': {
      id: '/_panel/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof PanelAppsAppIdRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/projects/$projectId': {
      id: '/_panel/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof PanelProjectsProjectIdRouteImport
      parentRoute: typeof PanelRoute
    }
  }
}

interface PanelRouteChildren {
  PanelIndexRoute: typeof PanelIndexRoute
  PanelAppsAppIdRoute: typeof PanelAppsAppIdRoute
  PanelProjectsProjectIdRoute: typeof PanelProjectsProjectIdRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelIndexRoute: PanelIndexRoute,
  PanelAppsAppIdRoute: PanelAppsAppIdRoute,
  PanelProjectsProjectIdRoute: PanelProjectsProjectIdRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PanelRoute: PanelRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
